import { createLazyFileRoute } from '@tanstack/react-router'

export const Route = createLazyFileRoute('/')({
	component: Root
})

function Root() {
	return (
		<div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
			<div>abcd</div>
		</div>
	)
}
